on:
   pull_request:
       branches:
        - develop
   workflow_dispatch:
   
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Setup dotnet
           uses: actions/setup-dotnet@v5
           with:
               dotnet-version: | 
                   9.0.x
         - uses: actions/checkout@v5
         - name: restore
           run: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj
         - name: build
           run: dotnet build --configuration Release src/Presentation/Nop.Web/Nop.Web.csproj 
         - name: test
           run: dotnet test src/Presentation/Nop.Web/Nop.Web.csproj --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults
         - name: publish
           run: dotnet publish --configuration Release src/Presentation/Nop.Web/Nop.Web.csproj --output published
         - name: Zip published folder
           run: zip -r published.zip published 
         - name: Publish test results
           uses: EnricoMi/publish-unit-test-result-action@v2
           with:
             files: |
                '**/TestResults/*.trx'
         - name: Upload published artifacts
           uses: actions/upload-artifact@v4
           with:
             name: nopCommerce-sep-2
             path: '**/TestResults/*.trx'
         
         
         
         
          
                   
